steps:
   # Clone a public repo and write its revision to a VERSION file. Hola
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    pwd && \
    git clone https://github.com/alvarohernandezrad/CI-CD-Benchmarking && \
    cd CI-CD-Benchmarking/web-app && \
    ls
    
- name: 'docker/compose:1.19.0'
  args: ['-f', 'CI-CD-Benchmarking/web-app/docker-compose.yml', 'up', '-d']
  
- id: Get Private Artifactory Address
  name: gcr.io/cloud-builders/gcloud
  entrypoint: /bin/bash
  args:
    - -c
    - |
      gcloud compute instances describe jfrog \
         --zone europe-west1-b \
      --format="value(networkInterfaces.networkIP)" >> _INTERNAL_IP_ADDRESS

  
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    curl http://$(cat _INTERNAL_IP_ADDRESS):3000/
