steps:
   # Clone a public repo and write its revision to a VERSION file. Hola
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    pwd && \
    git clone https://github.com/alvarohernandezrad/CI-CD-Benchmarking && \
    cd CI-CD-Benchmarking/web-app && \
    ls
    
- name: 'docker/compose:1.19.0'
  args: ['-f', 'CI-CD-Benchmarking/web-app/docker-compose.yml', 'up', '-d']
  
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    curl http://10.132.0.12:3000/
