steps:
   # Clone a public repo and write its revision to a VERSION file.
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    pwd && \
    git clone https://github.com/alvarohernandezrad/CI-CD-Benchmarking && \
    cd CI-CD-Benchmarking/web-app && \
    ls
    
- name: 'gcr.io/cloud-builders/git'
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    pwd
